version: "3.8"

services:

  app:
    build: ./nogran.email.api/
    restart: on-failure
    env_file: ./.env
    environment: 
      SPRING_MAIL_HOST: $SPRING_MAIL_HOST
      SPRING_MAIL_USERNAME: $SPRING_MAIL_USERNAME
      SPRING_MAIL_PORT: $SPRING_MAIL_PORT
      SPRING_MAIL_PASSWORD: $SPRING_MAIL_PASSWORD
      SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
      SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL
      NOGRAN_EMAIL_SENDER_PROPERTIES_TO: $NOGRAN_EMAIL_SENDER_PROPERTIES_TO
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
