name: nogran.email.api CI

on:
  push:
    branches:
      - dev
      - hml
      - prd
      - fix/*
      - feature/*
jobs:
  web-deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "docker-compose.yaml" up -d --build

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yaml" down
